Updated rivet2starkit to be able to locate itself
FossilOrigin-Name: 86905a925eea48c9b52a13780ee735b72de11716

diff --git a/bin/rivet2starkit b/bin/rivet2starkit
--- a/bin/rivet2starkit
+++ b/bin/rivet2starkit
@@ -1,7 +1,17 @@
 #! /bin/bash
 
 OUTPUT="$1"
-OURDIR="."
+OURSCP=$0
+if echo "${OURSCP}" | grep '/' >/dev/null; then
+	OURSCP="$(readlink -f "${OURSCP}")"
+else
+	OURSCP="$(which "${OURSCP}" 2>/dev/null)"
+	if [ -z "${OURSCP}" ]; then
+		echo 'Unable to find ourselves, aborting.' >&2
+		exit 1
+	fi
+fi
+OURDIR="$(dirname "${OURSCP}")"
 
 TCLPACK="$(readlink -f "${OURDIR}/../../starkit2exe/tclkits/tclkit-8.4.18-linux-x86")"
 SDXKIT="$(readlink -f "${OURDIR}/../../starkit2exe/support/sdx-1nrl.kit")"
